### ISSUE TITLE
Inability to craft Dislocator or Item Dislocator

### ISSUE THREAD

**Issue by eternalled** [ResqDiver1317/AC-Sauce-1_10_2_modpack#18]
Can not craft the dislocator item from Draconic Evolution.  Item comes up, but can not pull item out of either crafting stationo me system.  Similar to nugget issue.

**Comment by eternalled** [comment]
Further investigation shows that Item Dislocation does not work either.

**Comment by ResqDiver1317** [comment]
Will have to test, but one solution for this may be to remove the current recipes and put new recipes in using same items, but in a diff pattern with a custom recipe. Since this would be using ModTweaker/CraftTweaker which syncs to the client, this "should" resolve this issue.
If the restart does not fix it, I will try that next.

**Comment by eternalled** [comment]
confirmed working
