### ISSUE TITLE
Copper Wire crashes game

### ISSUE THREAD

**Issue by Noctleigh** [ResqDiver1317/AC-Sauce-1_10_2_modpack#25]
Reported by: Ace and Phel1X
Issue: Destroying copper wire from Tech Reborn causes the game to crash out.

**Comment by ResqDiver1317** [comment]
Client Side crash or Server? If client side, crash to desktop or just back to the connection screen?

**Comment by ResqDiver1317** [comment]
There seems to be several issues with IC2 and TechReborn. I have updates for all both and RebornCore that will be pushed tonight.
#26

**Comment by ResqDiver1317** [comment]
The IC2/TechReborn updates did not resolve either issue...

**Comment by ResqDiver1317** [comment]
Dev's solution is to remove optifine which is not a viable solution... They just don't want to fix the problem. Our solution is going to have to be to remove the recipes from them from the game. Since TechReborn and IC2 are made to work together, the IC2 copper wire should work in place for what they need to do.
