### ISSUE TITLE
Road Grid Size.

### ISSUE THREAD

**Issue by ResqDiver1317** [ResqDiver1317/AC-Sauce-1_10_2_modpack#3]
Still thinking out plot sizes, but the roads will be 6 wide made from black chisel concrete. 3 wide grass for the "Garden Path" for utilities, then 2 wide sidewalk made from a Light Gray Chisel Concrete (prob something with a nice sidewalky patter in it)

**Comment by ResqDiver1317** [comment]
Roads running East/West will be "Streets, numbered going up from Main Street using standard city formatting rules. Roads running North/South will be "Avenues" numbered going up from AdultCraft Avenue using standard city formatting. the Zero intersection will be Adultcraft Avenue and Main Street, located in front of the city hall/courthouse. (spawn is set inside the buildin 

Standard City Formatting is:

Streets North and West of Zero would be  # Street NW. 
South and East of Zero would be # St. SE. 
Since Main street is at Zero, it does not get the North/South qualifier. 

Since Avenues use names instead of numbers, the names would be different going east/west of Adultcraft Avenue. Example, the 1st N/S Road East of Adultcraft Avenue will be 2nd Ave, so depending on if it is North or South of Main Street, it would be 2nd Avenue NE or 2nd Avenue SE. The 1st N/S road West of Adultcraft Avenue will be 2nd Avenue NW or SW. 

Hopefully this makes sense to those of you that will be helping with the project. This standard is based on how many major cities do their street naming and as someone who has spent many years in emergency services responding to calls in parts of towns I was not familiar with, this system works very well. This also allows us to set "addresses" for each plot which will be helpful for if we implement a feature to allow users to "purchase" a heavier electric feed for a monthly fee (in game). 

Since there is no plugin that would easily manage this, one of the "jobs" in the game can be for a Electrician/Lineman whos job it is to maintain the power lines and collect the monthly fees for bigger power supplies. The Lineman(s) would have an office in city hall or in the main power plant and use bibliocraft clipboards to keep track. (the clipboards would make it easier for moderators/admins to assist with collection of fees and line issues).

And yea, I know I am way overthinking this project, but if this server idea takes off, planning it out better now will make it much easier later.

**Comment by Teyrz** [comment]
Resq I think what needs to be addressed more than looks is functionality of mods.  I love the idea of the Immersive engineering platform to be used for power generation and distrobution throughout the spawn and plot areas, however I think we need a city-scape sized infrastructure for providing additional building room for power generation, computer mainframes (Applied energistics, RS, etc), mining capabilities, and the like. 

Because we have additional mods now with other generation capabilities (such as ExU and EnderIO) we will have to monitor the way they're available in-game, or run the risk of completely circumventing the economy system.  Even if we can get them securely controlled, we need an area (or plot, maybe with a much higher monthly running cost?) for the building of the power plants to be constructed.

Maybe you can bring in the decoration designers (who is doing what by the way?) to come up with a few cool "construction" sites, one being a quarry-looking area for the miners, one for shops, etc etc etc.  This obviously means alot more work, but would be an interesting addition to the spawn plot idea if you think it could work.

I agree wholeheartedly about the idea of the jobs system integrating things like Linesman (power line maintenance), also IT support (hello? anyone know how to setup an ME system?) and maybe another form of electronics support (For things like RFtools screens, etc).   These are jobs that most people will be looking for, along with "landscape maintenance" (decocraft) and "city planner" or "Contractor" (A person could vie for a job to build the town library for instance).  The idea of a player-created spawn to me is very appealing, and could take a big damn load off the admin team, especially if there is a tangible reward at the end of it.  The only thing we'd have to do come up with: building material type, size, and design concept.  It's a good way to drive the economy, build the cityscape, and interest the players enough to change servers/keep players coming in with their friends.

How are you planning on doing the plugin for this? -Are- you going to try to get a plugin to handle this? If not, we may need to designate someone who is usually online to track and reward the players based on completion of jobs.

In regards to the maintenance jobs, would it be paid out weekly or daily?

Just food for thought, something to think on a bit

**Comment by Teyrz** [comment]
Actually it also bring to light a few other interesting concepts for player-jobs.  I was just sitting here re-reading what i wrote, and thought to myself "why are we doing all this work ? what else can we get players to do as a job?"---- Could even outsource to the mod-friendly players a job of going through the NEI and sorting out all of the possible work-arounds for power, or for quarrying, and paying a dividend based on how many exploits they can find.

What else could we get players to do for us? Putting everyone to work creating a community is the best way to keep people interested.  All we should have to do is come up with a Job board, and have at it.  Oh, and setup the main building areas.

**Comment by ResqDiver1317** [comment]
Lots of good points there Donkey (I hate when donkey has good points). Lets take this one at a time here
*It's not feasible to block players from making their own power if they want in town. The only way to stop that would be to block all power generation blocks which would prevent players who want to build out of town from making power. The city's power grid is simply to provide power for those that don't want to make their own. 

*If somebody wants to build their own power plant and sell power on their own, they can do so, but it's up to them to build their network (sending via dimensional transceivers, Flux Networks, or whatever), maintain it, and manage their own billing and such. I have no issues with competition, but disputes between players over did they pay, my power was disconnected and whoever I buy power from hasn't been on in a few days for me to pay so I can get my power back on, etc... will be between players and staff WILL NOT get involved in it. If you are paying for private power, and your provider flakes, then buy from someone else. A little competition never hurt anyone. Where the biggest issue in private power supplies will be is that there will be NO offline chunkloaders for players, or at minimum, a max of 1 offline loader may be purchased from the Donor store per player. 

*decoration sites. Thats a good idea. I'm putting you in charge of recruiting builders Donkey. 

*IT Techs Jobs, etc... - I'm gonna class those under Private Sector. If someone wants to offer themselves as a ME Tech, Landcaper, etc... they should buy a commercial plot to showcase what they do, and any hiring for those jobs would be a "contract" between the "business" and the person hiring them and they can pay eachother with the /pay commands.

*Utility Maintenance for the Govt, would be paid automatically via the economy plugin's job system (prob paid out hourly)

**Comment by skittishtrigger** [comment]
Honestly, unless there is something weird going on in a plot it should be more like a "home" anyways. The jobs system resq mentioned before should be what "equipment" or tools/blocks to be made for is used to obtain to a limited extent(wild builds excluded?) . I think people are thinking traditional modded/minecraft still here. Do you want a void miner in your house?  The power they generate will be limited anyways with size limitations (with the exception of factory plots?).  I like the wilds idea but I think that will cause the pack itself to become another regular modded pack. I feel/think that a lot of players, as has already been demonstrated, will just want to take off other players and "do" whatever.  They might have to have a pretty heavy restriction in order to really give the town thing a chance.  Maybe make the areas away from the town areas to expand the cities, and mining areas, public pools, etc, as if you were really building a town from scratch.
Not sure if I went off from the basic topic of the message but I think I caught the gist. lol

**Comment by Badeljamso** [comment]
there was mention of a bad side, maybe posible to make the 'wilds' more dangerous by prevention of claiming land/ mobds set to difficult outside of the town zone and mob griefing set to on outside of the town zone, encouraging players into the town where it is safer mob difficulty using simple gamerule commands.
im aware this might go against the flow of AC cominity ideals but just thinking outside of the box

**Comment by Teyrz** [comment]
I think I'd agree fully with skit here.  The trick will be to properly integrate the automation capabilities within the town itself only.  That will bring people together and be "forced" (i hate using that word) to play the pack the way it's being designed.  By limiting the pack to the town, however, you have to balance the open-world feel of minecraft within the confines of the town.  This will mean they must be allowed to build most of the town themselves, and be rewarded for the effort in order to make them feel like they accomplished something. 

RE: Resq-- ***decoration sites. Thats a good idea. I'm putting you in charge of recruiting builders Donkey.**   I honestly think the best builders we have are the players themselves.  Instead of recruiting them from the ranks, let them do it themselves.  Perhaps we don't build the entire city structure first, and instead block off locations for the town and mark them out as open plots to folks who want to build the labelled structure.  Not everyone builds things the same way, which is exactly how a minecraft town should look.

Land-Purchase: Is there a way to setup an in-game way of purchasing extra plots?  While the initial plot size is large enough to accomodate most people's builds, I think a fantastic way to create that feel of creativity and expansion would be to sell land in various parts of the town.  When you buy a mining plot, for example, you're purchasing the ore miner controller in the plot.  You can leave the rest of the ore miner blocks craftable, but keep the controllers blocked off.  Buying additional power generation plots would work the same way, and can be setup with little to no effort (aside from whoever's going to be terraforming the area to make it look like a mining biome lol) since the plot sizes could be as small as 10x10.  This is all depending on -IF- we can get a mod or plugin that will allow the automated functionality of buying those extra plots, since it would be a hell of a chore to do it manually.  The same renting rig we have on survival might work, as long as we can figure out how to deal with past-due rentals properly.

Hmm.  Thinking about Jam's response;  I once played on a server that had something called "extra" or "ultra" hard difficulty, which changed the way you can interact with things like cobble, stone, iron, etc.  It broke tools very quickly, and made mining through cobble (strip/branch mining) almost impossible, while still allowing cave-diving.  I'm sure it was a plugin.  Might be something worth looking at, to help remove the idea of simply wandering off into the wilderness to get away from town.  I also agree with the idea of removing mob griefing in the wilderness, though that generally just leads to people building up above the ground.

**Comment by ResqDiver1317** [comment]
Ok, so from looking over everyones ideas above, here is the thought coming into my head. Y'all think about this and let me knwo what you think.

1. "forcing" town progression. If I recall correctly, we can use GP's flags to regulate commands. Prevent Claiming in the wilderness an allow mob griefing there. The wilderness is open to everyone but it's a build at your own risk scenario. No protection of builds/materials/etc... I need to test but I think the only way to do this would be to place an admin claim on the whole map and only allow player claims in the plot subdivisions in the Town. If a group wants to start a small town somewhere, they can contact staff and "buy" the land for their town, then we can create a subdivision claim and town there for them which would allow player claims in their new town (this prob won't happen often so doing this manually shouldn't be an issue). Towns have a "Tax" rate meaning that if the players are not paying their taxes to the server, they lose their town. 

2. Buying extra plots - The actual buying of plots from the server is still an issue I'm trying to work out, but we have a couple options. Option 1, I can use my Alt Profile to create all the plots and put them up for sale (a limitation of the GP Towns feature is that the "server" can't sell plots, so using my alt will get around this and not mess with my personal economy). Option 2, don't bother selling the plots, just utilize the tax system. Tax is based on claim size so larger claims would have a higher tax. Don't pay tax, lose your claim. The downside of this is that it would not be possible to force players to claim their whole plot, meaning that a player could pick a large plot, but only claim what they want and have a lower tax. Thinking using Scuba to create/sell plots is going to be the best option. The rental system Tey referenced from standard would be good, except there is not a port of it for Sponge. There are a few plugs that offer similar, but none of them are very good and none of them offer what we would need it to do. 

3. Skit's comment about making areas away from towns to expand. I like that idea. First thing that came into mind would be like other towns with different things than what is at the main city. (a town with a pool and waterpark, small town in the mountains with a nice little hotel or 2 overlooking views and shops there with "nature" type stuff for sale. Limit what the server shops are selling to certain things in diff towns. Would like to get people after launch the server to help build a rail system to connect the diff towns. Ride train for free or use a teleport for a fee. (pretty sure we can do this with Nucleus or possibly a diff plugin. I know I've read about it in the documentation of something we are using on Sponge). Along with this, I believe GP allows teleportation to a players claims, so we could restrict the use of /home to premium only and only have a small number they can do. Non Premium can only "home" to their claims. 

4. Bad side of town. This is something I would like to do, thinking a neighborhood on the edge of town that is all run down, cheap plots available, but mob griefing is turned on.  

This is just my thoughts and I am completely open for discussion on it

**Comment by Teyrz** [comment]
RE: "bad side of town"-- could make that the starting area?  No one starts out rich! (aside from some lucky bastards).  Could add in a spawner in each plot for extra F-me moments starting out.

Like that idea best about wilderness being un-claimable.  Wild wild west.  Should pvp be on as well?

Sucks about the way you'll have to manage the plot purchasing.  Hopefully someone will code something up for us in the meantime.

RE: homeset--- suggestion: remove the ability to /sethome, and instead add /back as a premium feature if you want the rail system and teleportation system to be used.  Could add that in as a plot for purchase in the respective towns even.  

Saved the best for last.  The idea of satellite towns is fantastic.  I keep pushing the idea of player-built city, but maybe we do it with the towns instead.  Buying access into a town could give that open-world feeling of creativity.  The railroads through the wilderness is a great idea, however i think we need to set pre-claimed areas (or dirt roads) to offset the whole "wilderness is build at your own risk" scenario.  

Sorry i haven't been on to build anything, been busy as hell with camping/work here!

**Comment by Badeljamso** [comment]
player built towns outside of the main is a great idea, having to pay a tax to upkeep the town, seperate rulings and ideals, dependant on the town and its populace. maybe to nudge players to pay tax the certain buffs like monGriefing, keepInventory, player claims & game difficulty might change. so it wouldnt be absolutly needed to create a town but will make game play easier.

on the subject oftown creation im not sure if its possible but maybe a hefty fee and a minimum tally of players willing to set one up, nudging players who would use this to play together and not lone wolf it ( lol i would lone wolf it and make a huge base)

as for PvP out in the wilds i think it is a must 💯 player v player, town v town, it would after all be a completly optional venture to step out into the wilds, with there being a concencus that outside of the city/town it is dangerous and you probably will die i find quite attractive, some maverics might like it!
